<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AssemblyOriginatorKeyFile>..\..\build\Nodify.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Nodify\Nodify.csproj" />
    <ProjectReference Include="..\Nodify.Shared\Nodify.Shared.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)"/>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="$(XamlBehaviorsAvaloniaVersion)"/>
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)"/>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles SourceItemGroup="AvaloniaXaml" Include="**/*.xaml"/>
    <AdditionalFiles SourceItemGroup="AvaloniaXaml" Include="Editor/*.xaml"/>
    <AvaloniaResource Include="**/*.xaml" />
  </ItemGroup>
</Project>
