<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyOriginatorKeyFile>..\..\build\Nodify.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="$(XamlBehaviorsAvaloniaVersion)"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Themes\*.xaml" />
    <AvaloniaResource Include="Themes\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nodify\Nodify.csproj" />
  </ItemGroup>
</Project>
